### ISSUE TITLE
Setup de lint para o projeto do pokemon

### ISSUE THREAD

**Issue by frattezi** [vicio-code/primeiro-ciclo-de-mentoria#2]
Estudar e aprender a configurar o linter de um projeto. Para este caso, use o ESLINT com o padrão AirBnB. 

Para aceite:
 - Setup funcional do eslint no projeto existente.
 - Configurar Eslint para utilizar o airbnb-styleguide
 - Adicionar ao `package.json` um comando para lintar o código.
 - Configuração do Vscode

Referências:
- https://github.com/airbnb/javascript
- https://eslint.org/

**Comment by frattezi** [comment]
No link for the resolution, returning to dev.

**Comment by vicio-code** [comment]
https://github.com/vicio-code/poke-box/pull/2

Preciso de ajuda para entender o motivo dos conflitos nesse pull

**Comment by vicio-code** [comment]
https://github.com/vicio-code/base-projects/tree/js-react-base-project
