### ISSUE TITLE
Criar planejamento prévio do projeto

### ISSUE THREAD

**Issue by frattezi** [vicio-code/primeiro-ciclo-de-mentoria#4]
A aprtir de referências e idéias do seu site, elaborar um esboço (mesmo que a mão) do seu site como um todo,
deve ser entregue um esboço para cada página/ transição pensada, e junto a este esboço uma descrição dos componentes necessários.

**Comment by vicio-code** [comment]
https://www.figma.com/file/nkn42MkcuM4OC7IRArHWvH/PokeBox?node-id=0%3A1

**Comment by frattezi** [comment]
Fixes:
- Divide SearchBar and NavBar, since searchbar is generic enough to appear in other places of the app.
- What ???? means, for the last block I believe you would have at least 3 components to do there
- Filter can be Buttons, FilterHolder can be FIlterArea or Filter Component and it should be placed in the NavBar
- Your last component extends your page (or your user's monitor)?

Loved the figma design, use it to point a little better which component is which.

**Comment by frattezi** [comment]
If you are the person behind a task you should mark yourself as the Assignee for the issue.

**Comment by vicio-code** [comment]
Updated https://www.figma.com/file/nkn42MkcuM4OC7IRArHWvH/PokeBox?node-id=0%3A1
